// Neural vector search for `bee ask`, fused with BM25 via RRF.
//
// getVectorDb() decodes the corpus vectors baked into embeddings_gen.go
// (generated by cmd/genembeddings). embed() calls the configured API
// embedding endpoint at query time; when no endpoint is configured or the
// baked corpus is empty (DIM==0), vector search is skipped and BM25 handles
// retrieval alone — this is the default until genembeddings has been run.
package ask

import (
	"bytes"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"net/http"
	"net/url"
	"os"
	"sort"
	"strings"
	"sync"
	"time"
)

// VectorDb holds the dequantized corpus embedding matrix.
type VectorDb struct {
	IDs    []string
	Matrix [][]float64
}

var (
	vdbMu    sync.Mutex
	vdbCache *VectorDb
)

func getVectorDb() *VectorDb {
	vdbMu.Lock()
	defer vdbMu.Unlock()
	if vdbCache != nil {
		return vdbCache
	}
	vdbCache = &VectorDb{}
	dim := DIM // copy: DIM==0 is a valid baked value (empty corpus), and a
	// literal constant divisor of 0 below would be a compile error, not a
	// runtime one, if DIM were used directly.
	if dim <= 0 || VEC_B64 == "" {
		return vdbCache
	}
	raw, err := base64.StdEncoding.DecodeString(VEC_B64)
	if err != nil || len(raw) == 0 {
		return vdbCache
	}
	n := len(raw) / 2 / dim
	matrix := make([][]float64, n)
	for i := 0; i < n; i++ {
		row := make([]float64, dim)
		for j := 0; j < dim; j++ {
			off := (i*dim + j) * 2
			v := int16(binary.LittleEndian.Uint16(raw[off : off+2]))
			row[j] = float64(v) / float64(SCALE)
		}
		matrix[i] = row
	}
	vdbCache = &VectorDb{IDs: append([]string{}, VEC_IDS...), Matrix: matrix}
	return vdbCache
}

// cosineSimilarity returns 0 when either vector has zero norm.
func cosineSimilarity(a, b []float64) float64 {
	var dot, na, nb float64
	for i := range a {
		dot += a[i] * b[i]
		na += a[i] * a[i]
		nb += b[i] * b[i]
	}
	denom := math.Sqrt(na) * math.Sqrt(nb)
	if denom == 0 {
		return 0
	}
	return dot / denom
}

// searchVector ranks db entries by cosine similarity to queryEmb, oversamples
// topK*3 to absorb corpus items missing/empty at lookup time, then returns
// the first topK survivors.
func searchVector(queryEmb []float64, db *VectorDb, corpus []DocItem, topK int) []DocItem {
	type scored struct {
		idx   int
		score float64
	}
	scores := make([]scored, len(db.IDs))
	for i := range db.IDs {
		scores[i] = scored{i, cosineSimilarity(queryEmb, db.Matrix[i])}
	}
	sort.Slice(scores, func(i, j int) bool { return scores[i].score > scores[j].score })

	oversample := topK * 3
	if oversample > len(scores) {
		oversample = len(scores)
	}
	byID := make(map[string]*DocItem, len(corpus))
	for i := range corpus {
		byID[corpus[i].ID] = &corpus[i]
	}

	var out []DocItem
	for _, s := range scores[:oversample] {
		item, ok := byID[db.IDs[s.idx]]
		if !ok || strings.TrimSpace(item.Body) == "" {
			continue
		}
		out = append(out, *item)
		if len(out) >= topK {
			break
		}
	}
	return out
}

// rrfFusion merges two ranked lists by Reciprocal Rank Fusion: each item at
// (0-based) rank i in a list contributes 1/(k+i) to its score, summed across
// lists it appears in. k defaults to 60 when 0.
func rrfFusion(bm25, vector []DocItem, k int) []DocItem {
	if k == 0 {
		k = 60
	}
	scores := make(map[string]float64)
	var order []string
	byID := make(map[string]DocItem)
	add := func(list []DocItem) {
		for i, item := range list {
			if _, ok := byID[item.ID]; !ok {
				byID[item.ID] = item
				order = append(order, item.ID)
			}
			scores[item.ID] += 1 / float64(k+i)
		}
	}
	add(bm25)
	add(vector)

	sort.SliceStable(order, func(i, j int) bool { return scores[order[i]] > scores[order[j]] })

	out := make([]DocItem, len(order))
	for i, id := range order {
		out[i] = byID[id]
	}
	return out
}

// ─── Query-time embedding ──────────────────────────────────────────────────

var (
	embedMu    sync.Mutex
	embedTried bool
	embedCall  func(text string) ([]float64, error)
	warnedDim  bool
)

// embedQuery embeds text into the same vector space as the baked corpus.
// Returns (nil, nil) when no endpoint is configured, the API 404s, or the
// returned dimension doesn't match the baked corpus — all fall back to BM25.
func embedQuery(text string) ([]float64, error) {
	fn, err := getEmbedFn()
	if err != nil || fn == nil {
		return nil, nil
	}
	vec, err := fn(text)
	if err != nil {
		return nil, err
	}
	if len(vec) == 0 {
		return nil, nil
	}
	if len(vec) != DIM {
		if !warnedDim {
			fmt.Fprintf(os.Stderr, "[bee ask] embedding dim %d != baked %d — vector search disabled (BM25 only). Re-run cmd/genembeddings.\n", len(vec), DIM)
			warnedDim = true
		}
		return nil, nil
	}
	return vec, nil
}

// getEmbedFn resolves the embedding endpoint/auth once per process (a failed
// or unconfigured resolution is cached permanently — no retry).
func getEmbedFn() (func(string) ([]float64, error), error) {
	embedMu.Lock()
	defer embedMu.Unlock()
	if embedTried {
		return embedCall, nil
	}
	embedTried = true

	endpoint := embedEndpoint()
	if endpoint == "" {
		return nil, nil
	}

	bearer := apiKey()
	if bearer == "" && clientID() != "" && clientSecret() != "" {
		if base := lmURL(); base != "" {
			if isDatabricksHost(base) {
				dp := NewDatabricks(base, clientID(), clientSecret(), embedModel(), "")
				if tok, err := dp.getToken(); err == nil {
					bearer = tok
				}
			} else if tok, err := genericOIDCToken(base, clientID(), clientSecret()); err == nil {
				bearer = tok
			}
		}
	}

	model := embedModel()
	urlCandidates := []string{endpoint}
	if !strings.HasSuffix(endpoint, "/v1/embeddings") {
		if base := lmURL(); base != "" {
			urlCandidates = append(urlCandidates, joinURL(base, embedPath()))
			urlCandidates = append(urlCandidates, joinURL(base, "/serving-endpoints/"+url.PathEscape(model)+"/invocations"))
		}
	}

	embedCall = func(text string) ([]float64, error) {
		for _, u := range urlCandidates {
			vec, status, err := postEmbedding(u, text, model, bearer)
			if err == nil {
				return vec, nil
			}
			if status != 404 {
				return nil, err
			}
		}
		return nil, nil
	}
	return embedCall, nil
}

// genericOIDCToken exchanges client credentials for a bearer token via the
// generic OIDC endpoint — used when the LM host isn't Databricks (which has
// its own OAuth discovery in provider_databricks.go).
func genericOIDCToken(baseURL, clientID, clientSecret string) (string, error) {
	tokenURL := strings.TrimRight(baseURL, "/") + "/oidc/v1/token"
	form := url.Values{
		"grant_type":    {"client_credentials"},
		"scope":         {"all-apis"},
		"client_id":     {clientID},
		"client_secret": {clientSecret},
	}
	req, _ := http.NewRequest("POST", tokenURL, strings.NewReader(form.Encode()))
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	resp, err := (&http.Client{Timeout: 10 * time.Second}).Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("oidc token HTTP %d", resp.StatusCode)
	}
	raw, _ := io.ReadAll(resp.Body)
	var payload struct {
		AccessToken string `json:"access_token"`
	}
	if err := json.Unmarshal(raw, &payload); err != nil || payload.AccessToken == "" {
		return "", fmt.Errorf("no access_token in response")
	}
	return payload.AccessToken, nil
}

// postEmbedding POSTs one embedding request. status is the HTTP status (0 on
// transport error) so the caller can distinguish "try next URL" (404) from
// a hard failure.
func postEmbedding(endpoint, text, model, bearer string) ([]float64, int, error) {
	if len(text) > 2048 {
		text = text[:2048] // ponytail: byte-truncated, not rune-safe; queries are short ASCII in practice
	}
	body, _ := json.Marshal(map[string]string{"input": text, "model": model})
	req, _ := http.NewRequest("POST", endpoint, bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	if bearer != "" {
		req.Header.Set("Authorization", "Bearer "+bearer)
	}
	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil {
		return nil, 0, err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != 200 {
		return nil, resp.StatusCode, fmt.Errorf("embedding API returned %d at %s", resp.StatusCode, endpoint)
	}
	var payload struct {
		Data []struct {
			Embedding []float64 `json:"embedding"`
		} `json:"data"`
	}
	if err := json.Unmarshal(raw, &payload); err != nil {
		return nil, resp.StatusCode, err
	}
	if len(payload.Data) == 0 {
		return []float64{}, resp.StatusCode, nil
	}
	return payload.Data[0].Embedding, resp.StatusCode, nil
}
